### ISSUE TITLE
error when building Mouse reference

### ISSUE THREAD

**Issue by BitterWood** [mcgilldinglab/MATES#20]
Hi @Szym29 .
As I build the TE reference of Mouse via `python build_reference.py --species Mouse`, following [example](https://github.com/mcgilldinglab/MATES/tree/main/example), I meet two errors.
The first error is as follow:

> Traceback (most recent call last):
  File "/MATES/build_reference.py", line 179, in <module>
    main()
  File "/MATES/build_reference.py", line 76, in main
    if suffix == 'gff3':
UnboundLocalError: local variable 'suffix' referenced before assignment

I corrected this error by modifying the build_reference.py, exactly deleting these lines:
`if suffix == 'gff3':
        genes['Chromosome'] = genes['Chromosome'].astype(str)
        genes['Chromosome'] = 'Chr'+genes['Chromosome']`

Then I met the second error,

> cat: TE_full.csv: No such file or directory
cat: gene_bed.csv: No such file or directory
Traceback (most recent call last):
  File "MATES/build_reference.py", line 179, in <module>
    main()
  File "MATES/build_reference.py", line 117, in main
    removed_TE = pd.read_csv(f'{args.output_prefix}_removed_TE.txt',sep='\t', header=None, low_memory=False)
  File "miniconda3/envs/MATES/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "miniconda3/envs/MATES/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "miniconda3/envs/MATES/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "miniconda3/envs/MATES/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1679, in _make_engine
    return mapping[engine](f, **self.options)
  File "miniconda3/envs/MATES/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 555, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

I changed `TE_full.csv` and `gene_bed.csv` to `{args.output_prefix}_TE_full.csv` and `{args.output_prefix}_gene_bed.csv`, and the script threw another error:

> cat: TE_nooverlap.csv: No such file or directory

I change `TE_nooverlap.csv` to `{args.output_prefix}_TE_nooverlap.csv` and the script ran successfully.

**Comment by Szym29** [comment]
Hi @BitterWood ,

Thanks for pointing out these errors. I have fixed them and update the script. You can use git pull to fetch the latest code.

Thanks,
Yumin

**Comment by BitterWood** [comment]
Thank you for the nice tool  :)
