### ISSUE TITLE
Dependecies

### ISSUE THREAD

**Issue by pavelToman** [mcgilldinglab/MATES#6]
Hello MATES!
I am working for university in Gent (UGent) and I am installing sw for researchers on HPC. We are using EasyBuild for that.
Now I am trying to install MATES there, but have a hard time.
I need to install from sources and I can not use conda, just pip.

First problem is the dependencies in requirements.txt - why I need to install them? I found that there is `pymc3==3.11.4` and this sw needs `Theano-PyMC` but this one is old and do now support newer NumPy - so there is clash with yours `"numpy==1.25.2"` from `install_requires` in setup.py.
Hitting this error:
```
/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/cascadelake-ampere-ib/software/Theano/1.1.2-foss-2023a-PyMC/lib/python3.11/site-packages/theano/scalar/basic.py:2412: FutureWarning: In the future `np.bool` will be defined as the corres ponding NumPy scalar.
    self.ctor = getattr(np, o_type.dtype)
    Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/cascadelake-ampere-ib/software/Theano/1.1.2-foss-2023a-PyMC/lib/python3.11/site-packages/theano/__init__.py", line 83, in <module>
        from theano import scalar, tensor
    File "/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/cascadelake-ampere-ib/software/Theano/1.1.2-foss-2023a-PyMC/lib/python3.11/site-packages/theano/scalar/__init__.py", line 1, in <module>
        from .basic import *
    File "/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/cascadelake-ampere-ib/software/Theano/1.1.2-foss-2023a-PyMC/lib/python3.11/site-packages/theano/scalar/basic.py", line 2460, in <module>
        convert_to_bool = Cast(bool, name="convert_to_bool")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/cascadelake-ampere-ib/software/Theano/1.1.2-foss-2023a-PyMC/lib/python3.11/site-packages/theano/scalar/basic.py", line 2412, in __init__
        self.ctor = getattr(np, o_type.dtype)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/apps/gent/RHEL8/cascadelake-ib/software/SciPy-bundle/2023.07-gfbf-2023a/lib/python3.11/site-packages/numpy/__init__.py", line 313, in __getattr__
        raise AttributeError(__former_attrs__[attr])
    AttributeError: module 'numpy' has no attribute 'bool'.
    `np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
    The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
        https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'bool_'? (at easybuild/easybuild-framework/easybuild/framework/easyblock.py:3670 in _sanity_check_step)
```

Another problem is that I think you miss one dependency - `anndata`. When I run `from MATES import TE_quantifier` as a sanity check, it fails with:
```
  File "<string>", line 1, in <module>
  File "/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/cascadelake-ampere-ib/software/MATES/0.1.2-20240813-foss-2023a/lib/python3.11/site-packages/MATES/TE_quantifier.py", line 10, in <module>
    import anndata as ad
ModuleNotFoundError: No module named 'anndata'
```
Could you help me a little bit, please?

**Comment by Szym29** [comment]
Hi, 

Thank you for your interest in our tool. I will add the anndata in the dependency file and look into the pymc one.

Thanks,
Yumin

**Comment by Szym29** [comment]
Hi @pavelToman ,

I have removed the pymc3 along with some redundancies from the dependencies. Please let me know if you have any other questions when you install MATES in the HPC. I am very happy to assist you.

Thanks,
Yumin
